image:
  repository: 444152780810.dkr.ecr.us-east-1.amazonaws.com/lesson-5-dev-ecr
  tag: "15-2e079eb"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: ivan.boichuk.net
  path: /
  pathType: Prefix
  tls: true

config:
  DB_HOST: db
  DB_PORT: "5432"
  DB_NAME: djangodb
  DEBUG: "False"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

secret:
  create: true
  existingSecret: ""
  dbUser: djangouser
  dbPassword: ""
  djangoSecretKey: ""

postgresql:
  enabled: true
  image: postgres:15-alpine
  storage: 1Gi
  storageClass: ""
