image:
  repository: 444152780810.dkr.ecr.us-east-1.amazonaws.com/lesson-5-dev-ecr
  tag: "3-26e3350"
  pullPolicy: IfNotPresent

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: ivan.boichuk.net
  path: /
  pathType: Prefix
  tls: true

config:
  DB_HOST: db
  DB_PORT: "5432"
  DB_NAME: djangodb
  DEBUG: "False"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

probes:
  startup:
    enabled: true
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 18
  readiness:
    path: /
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  liveness:
    path: /
    initialDelaySeconds: 30
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 6

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

secret:
  create: true
  existingSecret: ""
  dbUser: djangouser
  dbPassword: ""
  djangoSecretKey: ""

postgresql:
  enabled: true
  image: postgres:15-alpine
  storage: 1Gi
  storageClass: ""
