{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: {{ .Release.Name }}-postgresql
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-postgresql
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-postgresql
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image | quote }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.config.DB_NAME | quote }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.existingSecret | default (printf "%s-app" .Release.Name) }}
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.existingSecret | default (printf "%s-app" .Release.Name) }}
                  key: DB_PASSWORD
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.postgresql.storageClass }}
  storageClassName: {{ .Values.postgresql.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
{{- end }}
