{{- if .Values.repository }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.repository.name | default "main-repo" | quote }}
  namespace: {{ .Values.repository.namespace | default "argocd" | quote }}
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: {{ .Values.repository.type | default "git" | quote }}
  url: {{ .Values.repository.url | quote }}
  {{- if .Values.repository.username }}
  username: {{ .Values.repository.username | quote }}
  {{- end }}
  {{- if .Values.repository.password }}
  password: {{ .Values.repository.password | quote }}
  {{- end }}
{{- end }}
